import { SchemeCategory, FarmerCategory } from '../scheme.model';
import { MockSchemeData } from '../types/scheme.types';

export const MOCK_SCHEMES: MockSchemeData[] = [
  {
    schemeName:    'PM-KISAN Samman Nidhi',
    schemeCode:    'PM-KISAN-2024',
    description:   'Income support of ₹6,000 per year to small and marginal farmer families to supplement their financial needs for procuring inputs.',
    benefits: [
      { type: 'Financial Assistance', description: 'Direct income support in three equal instalments', amount: 6000, unit: 'INR/year' },
    ],
    category:       SchemeCategory.SUBSIDY,
    targetAudience: 'Small and marginal farmers across India',
    state:          'All',
    eligibilityCriteria: {
      states:             [],
      minFarmSize:        null,
      maxFarmSize:        2,
      farmerCategories:   [FarmerCategory.SMALL, FarmerCategory.MARGINAL],
      cropTypes:          [],
      waterSources:       [],
      minAge:             18,
      maxAge:             null,
      genderRestriction:  'any',
      incomeLimitAnnual:  null,
      additionalCriteria: ['Landholder farmer families', 'Valid Aadhaar required'],
    },
    requiredDocuments:  ['Aadhaar Card', 'Bank Passbook', 'Land Records (Khasra/Khatauni)', 'Mobile Number'],
    applicationLink:    'https://pmkisan.gov.in',
    officialWebsite:    'https://pmkisan.gov.in',
    startDate:          new Date('2019-02-01'),
    endDate:            null,
    isActive:           true,
  },
  {
    schemeName:    'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
    schemeCode:    'PMFBY-2024',
    description:   'Crop insurance scheme providing comprehensive risk coverage for pre-sowing to post-harvest losses due to non-preventable natural risks.',
    benefits: [
      { type: 'Insurance Coverage', description: 'Coverage for crop loss due to natural calamities, pests, diseases', amount: null, unit: '% of sum insured' },
      { type: 'Premium Subsidy',    description: 'Heavily subsidised premiums: 2% for Kharif, 1.5% for Rabi, 5% for commercial crops', amount: null, unit: '% of sum insured' },
    ],
    category:       SchemeCategory.INSURANCE,
    targetAudience: 'All farmers growing notified crops',
    state:          'All',
    eligibilityCriteria: {
      states:             [],
      minFarmSize:        null,
      maxFarmSize:        null,
      farmerCategories:   [FarmerCategory.ALL],
      cropTypes:          [],
      waterSources:       [],
      minAge:             null,
      maxAge:             null,
      genderRestriction:  'any',
      incomeLimitAnnual:  null,
      additionalCriteria: ['Mandatory for loanee farmers', 'Optional for non-loanee farmers', 'Must grow notified crops'],
    },
    requiredDocuments: ['Aadhaar Card', 'Bank Account Details', 'Land Records', 'Sowing Certificate'],
    applicationLink:   'https://pmfby.gov.in',
    officialWebsite:   'https://pmfby.gov.in',
    startDate:         new Date('2016-04-13'),
    endDate:           null,
    isActive:          true,
  },
  {
    schemeName:    'Sub-Mission on Agricultural Mechanization (SMAM)',
    schemeCode:    'SMAM-2024',
    description:   'Promotes farm mechanization by providing financial assistance for purchase of agricultural machinery and equipment.',
    benefits: [
      { type: 'Subsidy on Equipment', description: '50% subsidy for small/marginal farmers on purchase of selected farm machinery', amount: 50, unit: '% of cost' },
      { type: 'Subsidy on Equipment', description: '25–40% subsidy for other categories', amount: 40, unit: '% of cost' },
    ],
    category:       SchemeCategory.EQUIPMENT,
    targetAudience: 'All categories of farmers',
    state:          'All',
    eligibilityCriteria: {
      states:             [],
      minFarmSize:        null,
      maxFarmSize:        null,
      farmerCategories:   [FarmerCategory.SMALL, FarmerCategory.MARGINAL, FarmerCategory.MEDIUM],
      cropTypes:          [],
      waterSources:       [],
      minAge:             18,
      maxAge:             null,
      genderRestriction:  'any',
      incomeLimitAnnual:  null,
      additionalCriteria: ['Must not have purchased similar equipment in last 3 years'],
    },
    requiredDocuments: ['Aadhaar Card', 'Land Records', 'Bank Account Details', 'Quotation from Authorised Dealer'],
    applicationLink:   'https://agrimachinery.nic.in',
    officialWebsite:   'https://agricoop.nic.in',
    startDate:         new Date('2014-01-01'),
    endDate:           null,
    isActive:          true,
  },
  {
    schemeName:    'Kisan Credit Card (KCC)',
    schemeCode:    'KCC-2024',
    description:   'Provides adequate and timely credit to farmers for their agricultural operations at concessional interest rates.',
    benefits: [
      { type: 'Credit Facility',   description: 'Revolving credit up to ₹3 lakh at 7% interest rate', amount: 300000, unit: 'INR credit limit' },
      { type: 'Interest Subvention', description: '2% interest subvention + 3% prompt repayment incentive', amount: 4, unit: '% effective rate' },
    ],
    category:       SchemeCategory.LOAN,
    targetAudience: 'All farmers, tenant farmers, sharecroppers, SHGs',
    state:          'All',
    eligibilityCriteria: {
      states:             [],
      minFarmSize:        null,
      maxFarmSize:        null,
      farmerCategories:   [FarmerCategory.ALL],
      cropTypes:          [],
      waterSources:       [],
      minAge:             18,
      maxAge:             75,
      genderRestriction:  'any',
      incomeLimitAnnual:  null,
      additionalCriteria: ['Must be engaged in agriculture or allied activities', 'Valid CIBIL score preferred'],
    },
    requiredDocuments: ['Aadhaar Card', 'PAN Card', 'Land Records', 'Passport Photo', 'Bank Account Details'],
    applicationLink:   'https://www.nabard.org',
    officialWebsite:   'https://www.nabard.org',
    startDate:         new Date('1998-08-01'),
    endDate:           null,
    isActive:          true,
  },
  {
    schemeName:    'Paramparagat Krishi Vikas Yojana (PKVY)',
    schemeCode:    'PKVY-2024',
    description:   'Promotes organic farming through cluster-based approach providing financial assistance for organic inputs and certification.',
    benefits: [
      { type: 'Financial Assistance', description: 'Financial support of ₹50,000/ha for 3 years for organic farming', amount: 50000, unit: 'INR/ha/3 years' },
    ],
    category:       SchemeCategory.ORGANIC_FARMING,
    targetAudience: 'Farmer clusters interested in organic farming',
    state:          'All',
    eligibilityCriteria: {
      states:             [],
      minFarmSize:        0.5,
      maxFarmSize:        null,
      farmerCategories:   [FarmerCategory.SMALL, FarmerCategory.MARGINAL, FarmerCategory.MEDIUM],
      cropTypes:          [],
      waterSources:       [],
      minAge:             18,
      maxAge:             null,
      genderRestriction:  'any',
      incomeLimitAnnual:  null,
      additionalCriteria: ['Minimum 50 farmers in a cluster', 'Minimum 50 acres contiguous land'],
    },
    requiredDocuments: ['Aadhaar Card', 'Land Records', 'Cluster Formation Certificate', 'Bank Account Details'],
    applicationLink:   'https://pgsindia-ncof.gov.in',
    officialWebsite:   'https://ncof.dacnet.nic.in',
    startDate:         new Date('2015-04-01'),
    endDate:           null,
    isActive:          true,
  },
  {
    schemeName:    'Mahila Kisan Sashaktikaran Pariyojana (MKSP)',
    schemeCode:    'MKSP-2024',
    description:   'Empowers women farmers by improving their skills, knowledge and access to resources and services in agriculture.',
    benefits: [
      { type: 'Training',            description: 'Free skill development and capacity building programmes', amount: null, unit: '' },
      { type: 'Financial Assistance', description: 'Input support and infrastructure for women farmer groups',  amount: null, unit: '' },
    ],
    category:       SchemeCategory.WOMEN_FARMERS,
    targetAudience: 'Women farmers and women farmer groups',
    state:          'All',
    eligibilityCriteria: {
      states:             [],
      minFarmSize:        null,
      maxFarmSize:        null,
      farmerCategories:   [FarmerCategory.ALL],
      cropTypes:          [],
      waterSources:       [],
      minAge:             18,
      maxAge:             null,
      genderRestriction:  'female',
      incomeLimitAnnual:  null,
      additionalCriteria: ['Must be engaged in agriculture', 'Preference to SHG members'],
    },
    requiredDocuments: ['Aadhaar Card', 'Bank Account Details', 'SHG/Group Membership Certificate (if applicable)'],
    applicationLink:   'https://aajeevika.gov.in',
    officialWebsite:   'https://aajeevika.gov.in',
    startDate:         new Date('2011-01-01'),
    endDate:           null,
    isActive:          true,
  },
  {
    schemeName:    'Pradhan Mantri Krishi Sinchayee Yojana (PMKSY)',
    schemeCode:    'PMKSY-2024',
    description:   'Ensures access to water for every field and improves water use efficiency through per drop more crop approach.',
    benefits: [
      { type: 'Subsidy on Irrigation', description: '55% subsidy on micro irrigation (drip/sprinkler) for small farmers', amount: 55, unit: '% of cost' },
      { type: 'Subsidy on Irrigation', description: '45% subsidy for other farmers', amount: 45, unit: '% of cost' },
    ],
    category:       SchemeCategory.IRRIGATION,
    targetAudience: 'All farmers seeking irrigation infrastructure',
    state:          'All',
    eligibilityCriteria: {
      states:             [],
      minFarmSize:        0.4,
      maxFarmSize:        null,
      farmerCategories:   [FarmerCategory.ALL],
      cropTypes:          [],
      waterSources:       [],
      minAge:             18,
      maxAge:             null,
      genderRestriction:  'any',
      incomeLimitAnnual:  null,
      additionalCriteria: ['Land should have water source or assured water supply'],
    },
    requiredDocuments: ['Aadhaar Card', 'Land Records', 'Water Source Proof', 'Bank Account Details'],
    applicationLink:   'https://pmksy.gov.in',
    officialWebsite:   'https://pmksy.gov.in',
    startDate:         new Date('2015-07-01'),
    endDate:           null,
    isActive:          true,
  },
  {
    schemeName:    'National Seed Programme (NSP)',
    schemeCode:    'NSP-2024',
    description:   'Provides quality seeds to farmers at subsidised rates to improve crop productivity and ensure food security.',
    benefits: [
      { type: 'Seed Subsidy', description: 'Distribution of certified seeds at 50% subsidised rates', amount: 50, unit: '% subsidy' },
    ],
    category:       SchemeCategory.SEED_SUPPORT,
    targetAudience: 'Small and marginal farmers',
    state:          'All',
    eligibilityCriteria: {
      states:             [],
      minFarmSize:        null,
      maxFarmSize:        4,
      farmerCategories:   [FarmerCategory.SMALL, FarmerCategory.MARGINAL],
      cropTypes:          [],
      waterSources:       [],
      minAge:             18,
      maxAge:             null,
      genderRestriction:  'any',
      incomeLimitAnnual:  150000,
      additionalCriteria: ['Must apply before sowing season'],
    },
    requiredDocuments: ['Aadhaar Card', 'Land Records', 'Income Certificate', 'Bank Account Details'],
    applicationLink:   'https://seednet.gov.in',
    officialWebsite:   'https://seednet.gov.in',
    startDate:         new Date('2005-01-01'),
    endDate:           null,
    isActive:          true,
  },
];
